name: SDK auto-tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Generate appsettings
        run: docker run --rm ghcr.io/payfurl/config-build:main > ./FunctionalTests/appsettings.json
      - name: Run tests
        run: dotnet test -nowarn:NU1701,NETSDK1138
