name: Manual workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.gitlab.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Check sources
        run: pwd && ls -la
      - name: Run tests
        run: docker run --rm -v ${PWD}:/app/tests registry.gitlab.com/payfurl/build/dotnet-sdk-test:latest
