name: Publish NuGet Package

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build NuGet package
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ${{ github.workspace }}\nupkg

      - name: logging
        run: dotnet nuget push --help

      - name: Publish NuGet package
        run: dotnet nuget push "${{ github.workspace }}\nupkg\*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json

      - name: Restore dependencies
        run: dotnet restore
